name: Continuous Integration

on: [push, pull_request]

env:
  PNPM_VERSION: "7"
  NODE_VERSION: "18.x"

jobs:
  test:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    name: "${{ matrix.os }} | Node ${{ matrix.node }}"

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: ${{ env.PNPM_VERSION }}
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - run: pnpm i --frozen-lockfile --production false
      - run: pnpm test
